# Generated by Django 6.0.5 on 2026-05-14 19:43

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('ceo', 'CEO / Orchestrator'), ('product', 'Product Strategist'), ('designer', 'UI/UX Designer'), ('engineer', 'Full-Stack Engineer'), ('marketer', 'Marketing Lead'), ('engagement', 'Engagement Lead'), ('analyst', 'Analytics Lead'), ('release', 'Release / Ops Lead'), ('buddy', 'Buddy Advisor')], max_length=32)),
                ('status', models.CharField(choices=[('idle', 'Idle'), ('thinking', 'Thinking'), ('working', 'Working'), ('blocked', 'Blocked'), ('done', 'Done'), ('error', 'Error')], default='idle', max_length=16)),
                ('current_task', models.CharField(blank=True, default='', max_length=400)),
                ('last_activity_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='agents.agent')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agents', to='projects.project')),
            ],
            options={
                'unique_together': {('project', 'role')},
            },
        ),
        migrations.CreateModel(
            name='AgentRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('input', models.TextField()),
                ('output', models.TextField(blank=True, default='')),
                ('error', models.TextField(blank=True, default='')),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('input_tokens', models.IntegerField(default=0)),
                ('output_tokens', models.IntegerField(default=0)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='runs', to='agents.agent')),
            ],
            options={
                'ordering': ('-started_at',),
            },
        ),
        migrations.CreateModel(
            name='AgentEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('status', 'status change'), ('thought', 'model text'), ('tool_call', 'tool invocation'), ('tool_result', 'tool result'), ('artifact', 'artifact written'), ('error', 'error')], max_length=20)),
                ('summary', models.CharField(blank=True, default='', max_length=400)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='agents.agent')),
                ('run', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='events', to='agents.agentrun')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
    ]
