# Generated by Django 6.0.5 on 2026-05-14 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agent',
            name='role',
            field=models.CharField(choices=[('ceo', 'CEO / Orchestrator'), ('product', 'Product Strategist'), ('designer', 'UI/UX Designer'), ('engineer', 'Engineering Lead'), ('frontend_eng', 'Frontend Engineer'), ('backend_eng', 'Backend Engineer'), ('qa_eng', 'QA Engineer'), ('marketer', 'Marketing Lead'), ('engagement', 'Engagement Lead'), ('analyst', 'Analytics Lead'), ('release', 'Release / Ops Lead'), ('buddy', 'Buddy Advisor')], max_length=32),
        ),
    ]
