# Generated by Django 6.0.5 on 2026-05-14 19:43

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('agents', '0001_initial'),
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Artifact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('spec', 'Specification'), ('design', 'Design'), ('code', 'Code'), ('doc', 'Document'), ('other', 'Other')], default='other', max_length=12)),
                ('path', models.CharField(max_length=500)),
                ('abs_path', models.CharField(max_length=1000)),
                ('content_preview', models.TextField(blank=True, default='')),
                ('size_bytes', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('agent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='artifacts', to='agents.agent')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='artifacts', to='projects.project')),
            ],
            options={
                'ordering': ('-updated_at',),
                'unique_together': {('project', 'path')},
            },
        ),
    ]
