# Generated by Django 6.0.5 on 2026-05-15 11:54

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artifacts', '0001_initial'),
        ('pipelines', '0002_pipelinerun_description'),
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PreviewVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.IntegerField()),
                ('html_content', models.TextField()),
                ('summary', models.CharField(blank=True, default='', help_text='Short plain-English description of what changed.', max_length=400)),
                ('author_role', models.CharField(blank=True, default='', max_length=32)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('pipeline_run', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='preview_versions', to='pipelines.pipelinerun')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preview_versions', to='projects.project')),
            ],
            options={
                'ordering': ('-version',),
                'unique_together': {('project', 'version')},
            },
        ),
    ]
