# Generated by Django 6.0.5 on 2026-05-14 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='default_approval_mode',
            field=models.CharField(default='after_run', max_length=24),
        ),
        migrations.AddField(
            model_name='user',
            name='per_role_approval',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
