# Generated by Django 6.0.5 on 2026-05-15 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pipelines', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pipelinerun',
            name='description',
            field=models.TextField(blank=True, default='', help_text='Optional founder note describing what this run is for.'),
        ),
    ]
